# GitHub Pages Jekyll config

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: EZMC
description: A server management CLI for self-hosting Minecraft Java Edition with AWS Elastic Container Service.
show_downloads: true
