version: 0.1.0.{build}
image: Ubuntu

environment:
  SOLUTION: ezmc-game-server
  STAGE: dev
  REGION: us-east-1
  AWS_ACCESS_KEY_ID:
    secure: YaEb8m87LlmMvmuP7ist7QLB4DS//lUTlMNzf3wL6dI=
  AWS_SECRET_ACCESS_KEY:
    secure: ceER808XvIxTANtUupVIv4DTSErDUfv9V3/4nEEvaFdtI7NfQEYb3RBcvssJroG9

for:
  - branches:
      only:
        - main
    environment:
      STAGE: main

install:
  - sh: npm install -g serverless

build: false
test: false

deploy_script:
  - sh: serverless deploy --stage $STAGE --region $REGION --verbose
      