version: 1.0.0.{build}
image: Ubuntu

environment:
  STAGE: main
  REGION: us-east-1
  AWS_ACCESS_KEY_ID:
    secure: YaEb8m87LlmMvmuP7ist7QLB4DS//lUTlMNzf3wL6dI=
  AWS_SECRET_ACCESS_KEY:
    secure: ceER808XvIxTANtUupVIv4DTSErDUfv9V3/4nEEvaFdtI7NfQEYb3RBcvssJroG9
  AWS_S3_BUCKET_TEMPLATES:
    secure: ZIC1zrNi8Z4n8H+OgmSWMSMCTIdQtCt2k1COru22DgE=
  AWS_S3_KEY_GAME_SERVER:
    secure: kndTMziPoF7lFmrQyEN3sw==

install:
  - sh: nvm use 16 # same as serverless provider
  - sh: npm ci --quiet

build: false
test: false

deploy_script:
  - sh: npx serverless deploy --stage $STAGE --region $REGION --verbose
