service: ezmc-game-service
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'main'}
  runtime: nodejs16.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  logs:
    frameworkLambda: true
    restApi:
      accessLogging: true
      executionLogging: true
  stackTags:
    Stage: ${self:provider.stage}
    Region: ${self:provider.region}

package:
  individually: true

functions:
  up:
    handler: ./src/functions/up/handler.up
    events:
      - http:
          path: up
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(./src/functions/up/schema.json)}
  down:
    handler: ./src/functions/down/handler.down
    events:
      - http:
          path: down
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(./src/functions/down/schema.json)}
