name: Build and Publish
run-name: ${{ github.event.head_commit.message }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install project
        run: npm ci --silent
      - name: Build
        run: npm run build
    #   - name: Publish
    #     run: npm publish
