name: Pipeline
run-name: ${{ github.event.head_commit.message }}
on: [push]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install project
        run: npm ci --silent
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
    #   - name: Publish
    #     run: npm publish
